<?php

namespace Taseera\UserBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOneRepository extends \Doctrine\ORM\EntityRepository
{
    // get the company that amont to specific subCategory
    public function getCompany($cat, $id)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('u')
            ->from('Taseera\UserBundle\Entity\UserOne', 'u')
            ->innerJoin('u.categories', 'c')
            ->where('c.id= :val')
            ->andWhere('c.subCategory = :value')
            ->addSelect('c')
            ->andWhere('u.accepted = :accept')
            ->setParameter('value', $cat)
            ->setParameter('val', $id)
            ->setParameter('accept', 1);

        ;
        return $queryBuilder
            ->getQuery()
            ->getResult()
            ;
    }

    //number of companies
    public function getCompaniesNumbers()
    {
        return $this->createQueryBuilder('u')
            ->select("COUNT(u)")
            ->where('u.accepted= :acc')
            ->setParameter('acc', 1)
            ->getQuery()
            ->getSinglescalarResult();
    }


}
