usertwo_index:
    path:     /
    defaults: { _controller: "TaseeraUserBundle:UserTwo:index" }
    methods:  GET

usertwo_show:
    path:     /{id}/show
    defaults: { _controller: "TaseeraUserBundle:UserTwo:show" }
    methods:  GET

usertwo_new:
    path:     /new
    defaults: { _controller: "TaseeraUserBundle:UserTwo:new" }
    methods:  [GET, POST]

usertwo_edit:
    path:     /{id}/edit
    defaults: { _controller: "TaseeraUserBundle:UserTwo:edit" }
    methods:  [GET, POST]

usertwo_delete:
    path:     /{id}/delete
    defaults: { _controller: "TaseeraUserBundle:UserTwo:delete" }
    methods:  DELETE
