<?php

namespace Taseera\BackendBundle\Repository;
use Taseera\BackendBundle\Entity\Category;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    //number of companies
    public function getItemNumbers()
    {
        return $this->createQueryBuilder('i')
            ->select("COUNT(i)")
            ->getQuery()
            ->getSinglescalarResult();
    }

    //search results
    public function getResults($word, $categorie, $user, $region)
    {
        $qb =  $this->createQueryBuilder('i');
        if($categorie) {
            $qb->innerJoin('i.categories', 'cat');
            $qb->where('cat.subCategory = :wordCategory')
                ->setParameter('wordCategory', $categorie);
            $qb->innerJoin('i.userOne', 'comp');
            $qb->andWhere('comp.accepted = :value')
                ->setParameter('value', 1);
            $qb->andWhere('i.nameItem LIKE :word')
                ->setParameter('word', '%' . $word . '%');
        }else{
            $qb->where('i.nameItem LIKE :word')
                ->setParameter('word', '%' . $word . '%');
            $qb->innerJoin('i.userOne', 'comp');
            $qb->andWhere('comp.accepted = :value')
                ->setParameter('value', 1);
        }
            return $qb->getQuery()->getResult();
    }
}
