<?php

namespace Taseera\BackendBundle\Repository;

/**
 * ViewsNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewsNumberRepository extends \Doctrine\ORM\EntityRepository
{
    //number of visitors
    public function getVisitorsNumbers()
    {
        return $this->createQueryBuilder('v')
            ->select("COUNT(v)")
            ->getQuery()
            ->getSinglescalarResult();
    }
}
