category_index:
    path:     /
    defaults: { _controller: "TaseeraBackendBundle:Category:index" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "TaseeraBackendBundle:Category:show" }
    methods:  GET

category_new:
    path:     /new
    defaults: { _controller: "TaseeraBackendBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "TaseeraBackendBundle:Category:edit" }
    methods:  [GET, POST]

category_edit_picture:
    path:     /editPictureCategory/{id}
    defaults: { _controller: TaseeraBackendBundle:Category:editPictureCategory }

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "TaseeraBackendBundle:Category:delete" }
    methods:  DELETE

category_deleted:
    path:     /{id}/delete_company
    defaults: { _controller: "TaseeraBackendBundle:Category:deleteCategory" }
    methods:  GET
