item_index:
    path:     /
    defaults: { _controller: "TaseeraBackendBundle:Item:index" }
    methods:  GET

item_show:
    path:     /{id}/show
    defaults: { _controller: "TaseeraBackendBundle:Item:show" }
    methods:  GET

item_new:
    path:     /new
    defaults: { _controller: "TaseeraBackendBundle:Item:new" }
    methods:  [GET, POST]

item_edit:
    path:     /{id}/edit
    defaults: { _controller: "TaseeraBackendBundle:Item:edit" }
    methods:  [GET, POST]

item_delete:
    path:     /{id}/delete
    defaults: { _controller: "TaseeraBackendBundle:Item:delete" }
    methods:  DELETE

item_deleted:
    path:     /{id}/delete_item
    defaults: { _controller: "TaseeraBackendBundle:Category:deleteItem" }
    methods:  GET
