#user_one_registration_register:
 #   path:     /
  #  defaults: { _controller: TaseeraUserBundle:RegistrationUserOne:register }

#user_two_registration_register:
 #   path:     /
  #  defaults: { _controller: TaseeraUserBundle:RegistrationUserOne:register }
