services:
#    taseera_user.example:
#        class: Taseera\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.profile.form.type:
        class: UserBundle\Form\ProfileUserOneFormType
        tags:
            - { name: form.type, alias: fos_user_company_profile }

    doctorsAdmin.form.profile:
        class: UserBundle\Form\ChangePasswordFormType
        tags:
            - { name: form.type, alias: doctorsAdmin_user_changePasswordFormType }
